name: Run

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install
      - run: yarn build
      - run: mkdir output
      - run: yarn start
        env:
          NODE_ENV: production
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: output
          commit_message: 'chore: deploy to GitHub Pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload traces
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: traces
          path: traces/*.json
